# Generated by Django 4.0.1 on 2024-04-14 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0013_alter_coursediary_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('s_name', models.CharField(max_length=20, null=True)),
                ('s_ktu_id', models.CharField(default='PTA21CS001', max_length=20)),
                ('batch', models.CharField(max_length=10)),
                ('output', models.BooleanField(default=True)),
                ('session_no', models.IntegerField()),
                ('c_code', models.CharField(max_length=7)),
                ('attendance', models.BooleanField(default=True)),
                ('viva_mark', models.IntegerField(default=0)),
                ('exp_no', models.IntegerField(default=0)),
                ('exp_comp', models.IntegerField(default=0)),
                ('next_exp', models.IntegerField(default=0)),
                ('course_diary', models.CharField(max_length=25)),
                ('total_hours', models.IntegerField(default=3)),
                ('presented_hours', models.IntegerField(default=3)),
                ('attendance_perc', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_code', models.CharField(max_length=7)),
                ('s_ktu_id', models.CharField(default='pta21cs024', max_length=10)),
                ('Ist_algorithm', models.IntegerField(default=30)),
                ('Ist_viva', models.IntegerField(default=20)),
                ('Ist_output', models.IntegerField(default=0)),
                ('Snd_algorithm', models.IntegerField(default=0)),
                ('Snd_viva', models.IntegerField(default=0)),
                ('Snd_output', models.IntegerField(default=0)),
                ('attendance', models.FloatField(default=100.0)),
                ('att_mark', models.IntegerField(default=10)),
                ('Total_internal', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(choices=[('cse', 'computer science and engieeering'), ('eee', 'electrical and electronics engineering'), ('ece', 'electronics and communication engineering')], max_length=3)),
                ('sem', models.IntegerField(default=1)),
                ('c_code', models.CharField(max_length=7)),
                ('scheme', models.IntegerField(default=4)),
                ('credit', models.IntegerField(default=4)),
                ('batch', models.CharField(max_length=10)),
                ('hours_taken', models.IntegerField(default=0)),
                ('lab_name', models.CharField(default='automatically updated', max_length=25)),
                ('clas', models.CharField(default='automatic', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='labs_in_curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(choices=[('cse', 'computer science and engieeering'), ('eee', 'electrical and electronics engineering'), ('ece', 'electronics and communication engineering')], max_length=3)),
                ('sem', models.IntegerField(default=1)),
                ('c_code', models.CharField(max_length=8)),
                ('lab_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter', models.TextField(max_length=150)),
                ('lab', models.ManyToManyField(related_name='schedules', to='login.labs')),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='fac_id',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='fac_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='stud_id',
        ),
        migrations.DeleteModel(
            name='Calender',
        ),
        migrations.RemoveField(
            model_name='coursediary',
            name='student',
        ),
        migrations.RemoveField(
            model_name='coursediary',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='stud_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.AlterUniqueTogether(
            name='teache',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teache',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='teache',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='teache',
            name='fac_id',
        ),
        migrations.RemoveField(
            model_name='teaches',
            name='fac_id',
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='periods',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='f_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='register_number',
            new_name='batch_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='f_password',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='fac_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='acad_details',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name',
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('cse', 'computer science and engieeering'), ('eee', 'electrical and electronics engineering'), ('ece', 'electronics and communication engineering')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='fid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='advisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='advising_students', to='login.faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='clas',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='dept_name',
            field=models.CharField(choices=[('cse', 'computer science and engieeering'), ('eee', 'electrical and electronics engineering'), ('ece', 'electronics and communication engineering')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='dob',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default='arun28@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='students',
            name='ktu_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AddField(
            model_name='students',
            name='roll_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='students',
            name='scheme',
            field=models.IntegerField(default=2015),
        ),
        migrations.AddField(
            model_name='students',
            name='sem',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='students',
            name='sid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='student_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='year_of_admission',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default='arun28@gmail.com', max_length=254),
        ),
        migrations.DeleteModel(
            name='academics',
        ),
        migrations.DeleteModel(
            name='Advisor',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseDiary',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teache',
        ),
        migrations.DeleteModel(
            name='Teaches',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
        migrations.AddField(
            model_name='labs',
            name='faculty_handling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handling_labs', to='login.faculty'),
        ),
        migrations.AddField(
            model_name='exam_marks',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marklists', to='login.labs'),
        ),
        migrations.AddConstraint(
            model_name='course_record',
            constraint=models.CheckConstraint(check=models.Q(('attendance', True), ('output', False), _connector='OR'), name='student not present constrain'),
        ),
        migrations.AlterUniqueTogether(
            name='course_record',
            unique_together={('s_name', 'date')},
        ),
    ]
